//@GeneratedCode
namespace SEContactManager.Common.Contracts
{
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial interface IContact : IIdentifiable
    {
        System.String FirstName { get; set; }
        System.String LastName { get; set; }
        System.String Email { get; set; }
        System.String PhoneNumber { get; set; }
        /// <summary>
        /// Copies the properties of another object to this instance.
        /// </summary>
        /// <param name="other">The object to copy the properties from.</param>
        void CopyProperties(IContact other)
        {
            other.CheckArgument(nameof(other));
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                FirstName = other.FirstName;
                LastName = other.LastName;
                Email = other.Email;
                PhoneNumber = other.PhoneNumber;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        /// <summary>
        /// This method is called before copying the properties of another object to the current instance.
        /// </summary>
        /// <param name="other">The object to copy the properties from.</param>
        /// <param name="handled">A boolean value that indicates whether the method has been handled.</param>
        partial void BeforeCopyProperties(IContact other, ref bool handled);
        /// <summary>
        /// This method is called after copying properties from another instance of the class.
        /// </summary>
        /// <param name="other">The other instance of the class from which properties were copied.</param>
        partial void AfterCopyProperties(IContact other);
    }
}
