//@GeneratedCode
namespace SEContactManager.Logic.Entities
{
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    partial class Contact : SEContactManager.Common.Contracts.IContact
    {
    }
}
