//@GeneratedCode
namespace SEContactManager.MVVMApp.ViewModels
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class ContactViewModel : GenericItemViewModel<Models.Contact>
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static ContactViewModel()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactViewModel"/> class (created by the generator.)
        /// </summary>
        public ContactViewModel()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called the object is being constraucted.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructed();

        /// <summary>
        /// Property 'FirstName' generated by the generator.
        /// </summary>
        public System.String FirstName
        {
            get
            {
                return Model.FirstName;
            }
            set
            {
                Model.FirstName = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'LastName' generated by the generator.
        /// </summary>
        public System.String LastName
        {
            get
            {
                return Model.LastName;
            }
            set
            {
                Model.LastName = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Email' generated by the generator.
        /// </summary>
        public System.String Email
        {
            get
            {
                return Model.Email;
            }
            set
            {
                Model.Email = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'PhoneNumber' generated by the generator.
        /// </summary>
        public System.String PhoneNumber
        {
            get
            {
                return Model.PhoneNumber;
            }
            set
            {
                Model.PhoneNumber = value;
                OnPropertyChanged();
            }
        }
    }
}
