//@GeneratedCode
namespace SEContactManager.MVVMApp.ViewModels
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class ContactViewModel : GenericItemViewModel<Models.Contact>
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static ContactViewModel()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactViewModel"/> class (created by the generator.)
        /// </summary>
        public ContactViewModel()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called the object is being constraucted.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructed();

        /// <summary>
        /// Property 'FirstName' generated by the generator.
        /// </summary>
        public System.String FirstName
        {
            get
            {
                OnFirstNameReading();
                return _firstName;
            }
            set
            {
                bool handled = false;
                OnFirstNameChanging(ref handled, value, ref _firstName);
                if (handled == false)
                {
                    _firstName = value;
                }
                OnPropertyChanged();
                OnFirstNameChanged();
            }
        }
        private System.String _firstName = string.Empty;
        partial void OnFirstNameReading();
        partial void OnFirstNameChanging(ref bool handled, System.String value, ref System.String _firstName);
        partial void OnFirstNameChanged();

        /// <summary>
        /// Property 'LastName' generated by the generator.
        /// </summary>
        public System.String LastName
        {
            get
            {
                OnLastNameReading();
                return _lastName;
            }
            set
            {
                bool handled = false;
                OnLastNameChanging(ref handled, value, ref _lastName);
                if (handled == false)
                {
                    _lastName = value;
                }
                OnPropertyChanged();
                OnLastNameChanged();
            }
        }
        private System.String _lastName = string.Empty;
        partial void OnLastNameReading();
        partial void OnLastNameChanging(ref bool handled, System.String value, ref System.String _lastName);
        partial void OnLastNameChanged();

        /// <summary>
        /// Property 'Email' generated by the generator.
        /// </summary>
        public System.String Email
        {
            get
            {
                OnEmailReading();
                return _email;
            }
            set
            {
                bool handled = false;
                OnEmailChanging(ref handled, value, ref _email);
                if (handled == false)
                {
                    _email = value;
                }
                OnPropertyChanged();
                OnEmailChanged();
            }
        }
        private System.String _email = string.Empty;
        partial void OnEmailReading();
        partial void OnEmailChanging(ref bool handled, System.String value, ref System.String _email);
        partial void OnEmailChanged();

        /// <summary>
        /// Property 'PhoneNumber' generated by the generator.
        /// </summary>
        public System.String PhoneNumber
        {
            get
            {
                OnPhoneNumberReading();
                return _phoneNumber;
            }
            set
            {
                bool handled = false;
                OnPhoneNumberChanging(ref handled, value, ref _phoneNumber);
                if (handled == false)
                {
                    _phoneNumber = value;
                }
                OnPropertyChanged();
                OnPhoneNumberChanged();
            }
        }
        private System.String _phoneNumber = string.Empty;
        partial void OnPhoneNumberReading();
        partial void OnPhoneNumberChanging(ref bool handled, System.String value, ref System.String _phoneNumber);
        partial void OnPhoneNumberChanged();
    }
}
