//@GeneratedCode
namespace SEContactManager.Logic.Contracts
{
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial interface IContactSet : IEntitySet<Entities.Contact>
    {
    }
}
