//@GeneratedCode
@startuml SEContactManager.Logic.Entities.Contact
+class Contact #whitesmoke {
    - String _firstName
    - String _lastName
    - String _email
    - String _phoneNumber
    ---
     + String getFirstName()
     + setFirstName(String value)
     + String getLastName()
     + setLastName(String value)
     + String getEmail()
     + setEmail(String value)
     + String getPhoneNumber()
     + setPhoneNumber(String value)
    ---
    + {static}Void Validate(Contact contact)
    ---
    + String get_FirstName()
    + Void set_FirstName(String value)
    + String get_LastName()
    + Void set_LastName(String value)
    + String get_Email()
    + Void set_Email(String value)
    + String get_PhoneNumber()
    + Void set_PhoneNumber(String value)
    + IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
}
+abstract class EntityObject #white {
    - Guid _id
    - Guid _guid
    ---
     + Guid getId()
     + setId(Guid value)
     + Guid getGuid()
     + setGuid(Guid value)
    ---
    + Guid get_Id()
    + Void set_Id(Guid value)
    + Guid get_Guid()
    + Void set_Guid(Guid value)
}
+abstract class DbObject #white {
}
interface IValidatableObject #lightgrey {
    + IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
}
interface IIdentifiable #lightgrey {
     + Guid getGuid()
     + setGuid(Guid value)
    ---
    + Guid get_Guid()
    + Void set_Guid(Guid value)
    + Void CopyProperties(IIdentifiable other)
}
EntityObject <|-- Contact
DbObject <|-- EntityObject
IValidatableObject ()- Contact
IIdentifiable ()- EntityObject
@enduml
